init:
  - git config --global core.autocrlf input

configuration: Release

assembly_info:
  patch: false

install:
  - cmd: nuget restore src/Akka.NET-Extensions.sln
  - ps: choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src/Akka.NET-Extensions.sln
  parallel: true
  verbosity: quiet

after_test:
  - cmd: nuget pack src/SchJan.Akka/SchJan.Akka.csproj -version ""%GitVersion_NuGetVersion%"" -prop ""target=%CONFIGURATION%""

artifacts:
  - path: '**\SchJan.*.nupkg'
  
cache:
  - src\packages -> **\packages.config

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true   
  
deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    api_key:
      secure: f8kuz/sBn2/omL6WhAC1RpipIT92gTBQoiu49QYwMvF3jnvCJDZSRBG5QYWev9tB
    on:
      branch: master
      appveyor_repo_tag: true
  
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    auth_token:
      secure: 3dDjg8MjJ3wbGtA9R37P42KEDSkGZiio/7ObP9WM7hpjFPkFdiKe957Q+om1tq4G
    on:
      branch: master
      appveyor_repo_tag: true 